### ISSUE TITLE
Using with custom page templates and custom post types.

### ISSUE THREAD

**Issue by Source3Media** [christophery/momentopress#1]
Hi Chris, im using the MomentoPress plugin and Momento 360 to on my clients website and I am trying to make it so that it will dynamically load the 360 image based on with sub site they are viewing. Im also trying to make it built into a custom page template and make it as easy for my client to utilize without having to remember a shortcode or modify any code,

What I am trying to do is the following
`<?php $args= array('post-type'=>'360', 'post-per-page'=>1);`
`$query = New WP_Query($args);`
`if($query->have_posts()):while($query->have_posts()):$query->the_post();`
`$url = the_field('link');`
`echo do_shortcode('[momentopress url=$url view=360];`
`endwhile;endif;wp_reset_postdata();`

If you have any ideas on how I could go about doing this, please get back to me!
If it's easier to email me, please do so at sphillips@source3media.com, thank you!

**Comment by christophery** [comment]
I'm not sure I fully understand your question. What do you mean by "sub site"? Please elaboration & clarify.

From your code example, all I can tell is that you're creating a custom post type of `360` and displaying 1 post per page and you're using a ACF field to pass a link into the `[momentopress]` shortcode.

**Comment by christophery** [comment]
Closed due to non-response.
